logo: "/images/Chris-Professional-Web_sm.png?raw=true"
title: Christopher Grace
description: > 
  Senior Business Intelligence <br>
  & Reporting Analyst <br>
  <br><br>
  Senior Business Intelligence and Reporting Analyst who leads the development of dashboards, analytics and productivity automation solutions.  Solutions enable actionable insights, confident decision-making, and streamlined processes for senior leadership and the teams they support. <br>   Former Senior Mechanical Engineer with a strong foundation developing new solutions through requirements gathering, analytical problem-solving, and a methodical approach to project delivery.
  <br><br>
  Ability to leverage analytical and BI tools including Tableau, Power BI, Alteryx, Power Query, SQL, and Python.<br>
  <br><br>
  Bachelor’s Degree in Mechanical Engineering <br>
  IBM Data Science Professional Certificate <br>
  Alteryx Designer Advanced Certification <br>
  <br><br>
  <a href="https://www.linkedin.com/in/cgrace2">View LinkedIn Profile</a>
  <br><br>
  <a href="https://public.tableau.com/app/profile/chrisg">View Tableau Public</a>

theme: jekyll-theme-minimal

# Google Analytics
google_analytics: UA-194794276-2

